services:
  gradio-agent:
    build:
      context: ../../../..
      dockerfile: LangChain/projects/dive-into-langgraph/app/Dockerfile
    container_name: gradio-agent-container
    ports:
      - "7860:7860"
    working_dir: /workspace/LangChain/projects/dive-into-langgraph/app
    env_file:
      - ../../../../.env
    environment:
      - TZ=Asia/Shanghai
